config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/disclaimer'
  get 'static_pages/privacy'
  devise_for :users
  root 'posts#index'
  resources :posts, except: :show do
    collection do
      get 'search'
      get 'select'
      get 'kana'
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :date_of_post, :price, presence: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 1, message: 'は1以上の半角数字のみ入力できます' }
  validates :select_yen, inclusion: [true, false]

  def self.search_month(current_user_id)
    posts = Post.where(user_id: current_user_id).where(
      date_of_post: Time.now.all_month
    ).order(date_of_post: :DESC, created_at: :DESC)
    monthly_price_sum = posts.sum(:price)
    monthly_post_count = posts.count
    [posts, monthly_price_sum, monthly_post_count]
  end

  def self.calc_post(posts)
    post_count = posts.count
    price_sum = posts.sum(:price)
    [post_count, price_sum]
  end

  def self.calc_donut(posts)
    price_true = posts.where(select_yen: true).sum(:price)
    price_false = posts.where(select_yen: false).sum(:price)
    price_total = (price_true + price_false).to_f
    price_true_percent = (price_true / price_total * 100).floor(1)
    [{ 'Good yen!': price_true, 'あと一歩': price_false }, price_true_percent]
  end

  def self.set_month(posts, year, first_month, last_month, array)
    first_month.upto(last_month) do |i|
      first_day = Time.new(year, i, 1)
      month_post = posts.select(:select_yen, :price).where(date_of_post: first_day.all_month)
      price_true = month_post.where(select_yen: true).sum(:price)
      price_false = month_post.where(select_yen: false).sum(:price)

      array[0].push(["#{year}-#{i}月", price_true])
      array[1].push(["#{year}-#{i}月", price_false])
    end
    array
  end

  def self.calc_monthly_average(monthly_price_sums, price_sum)
    month_count = monthly_price_sums.dig(0, :data).count
    (price_sum / month_count)
  end

  def self.calc_column_and_bar(params, posts, price_sum)
    gteq = if params.dig(:q, :date_of_post_gteq).present?
             params.dig(:q, :date_of_post_gteq).to_date
           else
             posts.last[:date_of_post]
           end
    lteq = if params.dig(:q, :date_of_post_lteq).present?
             params.dig(:q, :date_of_post_lteq).to_date
           else
             posts.first[:date_of_post]
           end

    old_year = gteq.year
    old_month = gteq.month
    new_year = lteq.year
    new_month = lteq.month

    price_true_sums = []
    price_false_sums = []
    array = [price_true_sums, price_false_sums]

    if old_year == new_year
      set_month(posts, old_year, old_month, new_month, array)
    else
      january = 1
      december = 12
      set_month(posts, old_year, old_month, december, array)
      old_year += 1
      while old_year != new_year
        set_month(posts, old_year, january, december, array)
        old_year += 1
      end
      set_month(posts, old_year, january, new_month, array)
    end

    monthly_price_sums = [{ name: 'Good yen!', data: price_true_sums }, { name: 'あと一歩', data: price_false_sums }]
    [monthly_price_sums, calc_monthly_average(monthly_price_sums, price_sum)]
  end

  def self.calc_period(current_user_id)
    period = {}
    posts = Post.select(:date_of_post).where(user_id: current_user_id).order(date_of_post: :DESC)
    if posts.present?
      first_post = posts.last[:date_of_post]
      last_post = posts.first[:date_of_post]
      day = (last_post - first_post + 1).to_i
      period = { first_post: first_post, last_post: last_post, day: day }
    end
    period
  end

  def self.make_query(q)
    querys = []
    if q.blank?
      querys << '・すべて表示'
    else
      if q[:date_of_post_gteq].present? || q[:date_of_post_lteq].present?
        querys << "・#{q[:date_of_post_gteq]} 〜 #{q[:date_of_post_lteq]}"
      end

      if q[:price_gteq].present? && q[:price_lteq].present?
        querys << "・#{q[:price_gteq].to_i.to_s(:delimited)}円 〜 #{q[:price_lteq].to_i.to_s(:delimited)}円"
      else
        querys << "・#{q[:price_gteq].to_i.to_s(:delimited)}円 〜" if q[:price_gteq].present?
        querys << "・〜 #{q[:price_lteq].to_i.to_s(:delimited)}円" if q[:price_lteq].present?
      end

      if q[:select_yen_eq].present?
        querys << '・「Good yen!」のみ' if q[:select_yen_eq] == 'true'
        querys << '・「あと一歩」のみ' if q[:select_yen_eq] == 'false'
      end

      querys << "・メモ①：#{q[:memo1]}" if q[:memo1].present?
      querys << "・メモ②：#{q[:memo2]}" if q[:memo2].present?
      querys << '・すべて表示' if querys.blank?
    end
    querys
  end

  private_class_method :set_month, :calc_monthly_average
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :destroy]

  def index
  end

  def new
    @post = Post.new
    set_list
    return render :kana_new if request.referer.include?('kana')
  end

  def create
    @post = Post.new(post_params)
    set_list
    if @post.save
      flash[:notice] = '1件の記録を「保存」しました。'
      return redirect_to new_post_path(type: 'kana') if request.referer.include?('kana')

      redirect_to new_post_path
    else
      render :new
    end
  end

  def edit
    session[:previous_url] = request.referer || new_post_path
    return render :kana_edit if request.referer.include?('kana')
  end

  def update
    if @post.update(post_params)
      flash[:notice] = '1件の記録を「変更」しました。'
      redirect_to session[:previous_url]
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = '1件の記録を「削除」しました。'
    redirect_back(fallback_location: new_post_path)
  end

  def search
    set_memo_search
    @q = current_user.posts.ransack(params[:q])
    posts = @q.result.order(date_of_post: :DESC, created_at: :DESC)
    @post_count, @price_sum = Post.calc_post(posts)
    @pagy, @posts = pagy(posts, items: 10)
    @querys = Post.make_query(params[:q])
    @period = Post.calc_period(current_user.id)

    if params[:show_donut]
      @price_sums, @price_true_percent = Post.calc_donut(posts) if posts.present?
      render :donut
    elsif params[:show_column] || params[:show_bar]
      @monthly_price_sums, @monthly_price_average = Post.calc_column_and_bar(params, posts, @price_sum) if posts.present?
      if params[:show_column]
        render :column
      else
        render :bar
      end
    elsif params[:export_csv]
      send_posts_csv(posts)
    elsif request.referer.include?('kana')
      render :kana_search
    else
      render :search
    end
  end

  def select
    post = current_user.posts.where(select_yen: true)
    return if post.blank?

    @post_count = post.count
    @post = post.sample
  end

  def kana
  end

  private

  def post_params
    params.require(:post).permit(:date_of_post, :select_yen, :price, :memo1, :memo2).merge(user_id: current_user.id)
  end

  def set_list
    posts, @monthly_price_sum, @monthly_post_count = Post.search_month(current_user.id)
    @pagy, @posts = pagy(posts, items: 10)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def move_to_index
    redirect_to root_path unless current_user.id == @post.user_id
  end

  def set_memo_search
    if params[:q]&.dig(:memo1).present?
      squished_keywords = params[:q][:memo1].squish
      params[:q][:memo1_cont_any] = squished_keywords.split(' ')
    end
    return true if params[:q]&.dig(:memo2).blank?

    squished_keywords = params[:q][:memo2].squish
    params[:q][:memo2_cont_any] = squished_keywords.split(' ')
  end

  def send_posts_csv(posts)
    bom = "\xEF\xBB\xBF"
    csv_data = CSV.generate(bom, force_quotes: true) do |csv|
      header = %w[日付 金額 Good_yen? メモ1 メモ2]
      csv << header

      posts.each do |post|
        values = [post.date_of_post, post.price, post.select_yen, post.memo1, post.memo2]
        csv << values
      end
    end
    time_now = Time.now.strftime('%Y%m%d')
    send_data(csv_data, filename: "記録一覧#{time_now}.csv", type: :csv)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="form_post">
  <%= form_with model: post, local: true do |f| %>
    <div class='flash-message'>
      <%= render 'shared/error_messages', model: f.object %>
    </div>
    <table class="form_set_width_max">
      <tbody>
        <tr>
          <td class="form_set_width"><span class="indispensable">必須</span></td>
          <td class="form_set_width"><%= f.label :date_of_post, '日付' %></td>
          <td class="form_align_left">
            <% if controller.action_name == 'new' %>
              <%= f.date_field :date_of_post, value: Date.today %>
            <% else %>
              <%= f.date_field :date_of_post %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td class="form_set_width"><span class="indispensable">必須</span></td>
          <td><%= f.label :price, '金額' %></td>
          <td class="form_price_size form_align_left"><%= f.number_field :price, style: "width:70%", min: 1, placeholder:'半角数字のみ' %> 円</td>
        </tr>
        <tr>
          <td class="form_set_width"></td>
          <td><%= f.label :memo1, 'メモ①' %></td>
          <td class="form_memo_size form_align_left">
            <%= f.text_area :memo1, style: "width:100%", placeholder:'100文字まで', maxlength: 100, class: 'form_memo' %>
          </td>
        </tr>
        <tr>
          <td class="form_set_width"></td>
          <td><%= f.label :memo2, 'メモ②' %></td>
          <td class="form_memo_size form_align_left">
            <%= f.text_area :memo2, style: "width:100%", placeholder:'100文字まで', maxlength: 100, class: 'form_memo' %>
          </td>
        </tr>
        <tr>
          <td class="form_set_width"><span class="indispensable">必須</span></td>
          <td colspan="2">
            <b>Good yen?</b>
            <%= link_to root_path(anchor: 'good_yen_info'), data: { confirm: 'トップページの「よくある質問」欄へ移動します。よろしいですか？' } do %>
              <i class="fa-solid fa-circle-question fa-lg fa-fw" alt="Good yen! 説明欄へのリンク"></i>
            <% end %><br>
            <span class="under-line" id="insert_point">いいお金の使い方でしたか？</span>
            <div id="radio_button">
              <%= f.radio_button :select_yen, true %>
              <%= f.label :select_yen, 'はい！', value: true %>
              <%= f.radio_button :select_yen, false %>
              <%= f.label :select_yen, 'あと一歩', value: false %>
            </div>
          </td>
        </tr>
        <tr>
          <td colspan="3">
            <%= f.button class: 'btn btn-default btn-outline-success', name: "submit" do %>
              <i class="fa-solid fa-calculator fa-lg fa-fw" aria-hidden="true"></i>保存する
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>

app/views/posts/_kana_post_list.html.erb
<tr>
  <td rowspan="2" class="set-width-logo table-border">
    <% if post.select_yen %>
      <%= image_tag 'yen-logo.png', alt: "Good yen!", class: "yen-logo-list" %>
    <% end %>
  </td>
  <td class="nowrap">
    <%= post.date_of_post %>(<%= %w(にち げつ か すい もく きん ど)[post.date_of_post.wday] %>)
  </td>
  <td class="nowrap align-right"><%= post.price.to_s(:delimited) %>えん</td>
  <td rowspan="2" class="set-width table-border align-right">
    <%= link_to edit_post_path(post.id, type: 'kana') do %>
      <i class="fa-solid fa-pen fa-lg fa-fw" alt="編集のマーク"></i>
    <% end %>
    <%= link_to  post_path(post.id), method: :delete, data: { confirm: 'さくじょして いいですか? このそうさは もとに もどせません。' } do %>
      <i class="fa-solid fa-trash fa-lg" alt="削除のマーク"></i>
    <% end %>
  </td>
</tr>
<tr>
  <td class="post-list-memo table-border">
    <% if post.memo1.present? %>
      <%= safe_join(post.memo1.split("\n"),tag(:br)) %>
    <% end %>
  </td>
  <td class="post-list-memo table-border">
    <% if post.memo2.present? %>
      <%= safe_join(post.memo2.split("\n"),tag(:br)) %>
    <% end %>
  </td>
</tr>

app/views/posts/_kana_query.html.erb
<div class="heading-name">
  <h5><%= current_user.nickname %>さんの きろく</h5>
</div>
<ul class="messages">
  <li class="heading-name-line"><li>
</ul>
<div class="align_center">
  <% if period.present? %>
    つづいた きかん：<%= period[:day] %>にち<br>（<%= period[:first_post] %> 〜 <%= period[:last_post] %>）<br>
  <% end %>
  <div class="form_post form_query">
    <i class="fa-solid fa-magnifying-glass fa-lg fa-fw" aria-hidden="true"></i>けんさく じょうけん<br>
    <% querys.each do |query| %>
      <%= query %><br>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="contents">
    <h5 class="align_center">記録フォーム（編集）</h5>
    <%= render partial: 'form', locals: { post: @post } %>
  </div>
</div>

app/views/posts/kana.html.erb
<div class="container">
  <div class="contents">
    <div class='flash-message'><%= notice %></div>
    <div class='kana'>
      <%= link_to 'きろくする', new_post_path(type: 'kana'), class: 'margin_kana' %>
      <%= link_to 'ふりかえる', search_posts_path(type: 'kana') %>
    </div>
    <div class="heading-name">
      <h5 class="align_center">ひらがなに しました。</h5>
    </div>
    <ul class="messages">
      <li class="heading-name-line"><li>
    </ul>
    <div class="align_center">
      <br>
      ・もとに もどしたい ときは ひだりうえの<br>あいこんを おしてください。<br><br>
      ・ひらがなに なるのは <br>「きろくする」と 「ふりかえる」の<br>ぺーじ だけです。<br><br>
      ・かんじの ままの ぶぶんも あります。
    </div>
  </div>
</div>

app/views/posts/kana_edit.html.erb
<div class="container">
  <div class="contents">
    <h5 class="align_center">きろくふぉーむ（へんこう）</h5>
    <%= render partial: 'kana_form', locals: { post: @post } %>
  </div>
</div>

app/views/posts/kana_new.html.erb
<div class="container">
  <div class="contents">
    <div class='flash-message'><%= notice %></div>
    <div class='kana'>
      <%= link_to 'きろくする', new_post_path(type: 'kana'), class: 'margin_kana' %>
      <%= link_to 'ふりかえる', search_posts_path(type: 'kana') %>
    </div>
    <%# 結果一覧 %>
    <h5 class="align_center">きろく ふぉーむ</h5>
    <%= render partial: 'kana_form', locals: { post: @post } %>
    <div class="heading-name">
      <h5 class="set-margin"><%= current_user.nickname %>さんの きろく（<%= Time.now.month %>がつ）</h5>
    </div>
    <ul class="messages">
      <li class="heading-name-line"><li>
    </ul>
    <div class="align_center"><%= @monthly_post_count %> けん | ごうけい：<%= @monthly_price_sum.to_s(:delimited) %>えん</div>
    <% if @posts.present? %>
      <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
      <table>
        <%= render partial: 'kana_post_list', collection: @posts, as: "post" %>
      </table>
      <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
    <% end %>
  </div>
</div>

app/views/posts/kana_search.html.erb
<div class="container">
  <div class="contents">
    <div class='flash-message'><%= notice %></div>
    <div class='kana'>
      <%= link_to 'きろくする', new_post_path(type: 'kana'), class: 'margin_kana' %>
      <%= link_to 'ふりかえる', search_posts_path(type: 'kana') %>
    </div>
    <%# 検索フォーム %>
    <h5 class="align_center">けんさく ふぉーむ</h5>
    <div class="form_post">
      <%= search_form_for @q, url: search_posts_path(anchor: 'post_list') do |f| %>
        <table class="form_set_width_max">
          <tbody>
              <td class="form_set_width_search"><%= f.label :date_of_post_gteq, 'ひにち' %></td>
              <td class="form_align_left">
                <%= f.date_field :date_of_post_gteq, id: "date1" %> から<br>
                <%= f.date_field :date_of_post_lteq, id: "date2" %> まで
              </td>
            </tr>
              <td><%= f.label :price_gteq, 'きんがく' %></td>
              <td class="form_price_size form_align_left">
                <%= f.number_field :price_gteq, style: "width:60%", placeholder: 'はんかく すうじ', id: "price1" %> えんから<br>
                <%= f.number_field :price_lteq, style: "width:60%", placeholder: 'はんかく すうじ', id: "price2" %> えんまで
              </td>
            </tr>
            <tr>
              <td><%= f.label :memo1, 'めも①' %></td>
              <td class="form_memo_size form_align_left">
                <%= f.text_field :memo1, style: "width:80%", class: 'form_memo', placeholder: 'いくつも いれられます', value: params[:q]&.dig(:memo1), id: "memo1" %>
              </td>
            </tr>
            <tr>
              <td><%= f.label :memo2, 'めも②' %></td>
              <td class="form_memo_size form_align_left">
                <%= f.text_field :memo2, style: "width:80%", class: 'form_memo', placeholder: 'いくつも いれられます', value: params[:q]&.dig(:memo2), id: "memo2" %>
              </td>
            </tr>
            <tr>
              <td class="form_set_width_search">ぐっど<br>えん？</td>
              <td class="form_align_left">
                <%= f.radio_button :select_yen_eq, '', id: "select_yen" %>
                <%= f.label :select_yen_eq, 'してい なし', value: '' %><br>
                <%= f.radio_button :select_yen_eq, true %>
                <%= f.label :select_yen_eq, '「ぐっど えん！」のみ', value: true %><br>
                <%= f.radio_button :select_yen_eq, false %>
                <%= f.label :select_yen_eq, '「あといっぽ」のみ', value: false %>
              </td>
            </tr>
            <tr class="form_set_height">
              <td colspan="2">
                <%= f.button class: 'btn btn-outline-success', name: 'kana' do %>
                  <i class="fa-solid fa-magnifying-glass fa-lg fa-fw" aria-hidden="true"></i>
                  いちらん
                <% end %>
                <%= f.button class: 'btn btn-outline-success', name: 'export_csv', data: { confirm: "げんざいの じょうけんで しぼりこんで しゅつりょくします。\nよろしいですか？"} do %>
                  <i class="fa-solid fa-file-lines fa-lg fa-fw" aria-hidden="true"></i>
                  しゅつりょく
                <% end %>
              </td>
            </tr>
            <tr class="form_set_height">
              <td colspan="2">
                <%= f.button class: 'btn btn-outline-success', name: 'show_donut' do %>
                  <i class="fa-solid fa-chart-pie fa-lg fa-fw" alt="円グラフ"></i>
                  まる
                <% end %>
                <%= f.button class: 'btn btn-outline-success', name: 'show_column' do %>
                  <i class="fa-solid fa-chart-simple fa-lg fa-fw" alt="縦向き棒グラフ"></i>
                  たて
                <% end %>
                <%= f.button class: 'btn btn-outline-success', name: 'show_bar' do %>
                  <i class="fa-solid fa-chart-simple fa-lg fa-fw bar_rotate" alt="横向き棒グラフ"></i>
                  よこ
                <% end %>
              </td>
            </tr>
            <tr>
              <td colspan="2" class="align_center">
                <a href="/" id="reset_btn">
                  <i class="fa-solid fa-arrow-rotate-right fa-lg fa-fw" aria-hidden="true"></i>
                  けんさく じょうけんを けす
                </a>
            <tr>
          </tbody>
        </table>
      <% end %>
    </div>
    <%# /検索フォーム %>
    <%# 結果一覧 %>
    <div class="content" id="post_list">
      <div class="align_center">
        <%= render partial: 'kana_query', locals: { period: @period, querys: @querys } %>
        <%= @post_count %> けん | ごうけい：<%= @price_sum.to_s(:delimited) %>えん<br>
      </div>
      <% if @posts.present? %>
        <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
        <div class="sort_info">＊こうもく めいを おすと <b>ならべかえ</b> できます</div>
          <table>
            <thead>
              <tr>
                <th rowspan="2" class="set-width-logo"><%= sort_link(@q, :select_yen, 'ぐっど えん？') %></th>
                <th><%= sort_link(@q, :date_of_post, 'ひにち') %></th>
                <th class="nowrap"><%= sort_link(@q, :price, 'きんがく') %></th>
                <th rowspan="2" class="set-width"></th>
              </tr>
              <tr class="table-border">
                <th><%= sort_link(@q, :memo1, 'めも①') %></th>
                <th><%= sort_link(@q, :memo2, 'めも②') %></th>
              </tr>
            <thead>
            <tbody>
              <%= render partial: 'kana_post_list', collection: @posts, as: "post" %>
            <tbody>
          </table>
        <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
      <% end %>
    </div>
    <%# /結果一覧 %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="contents">
    <div class='flash-message'><%= notice %></div>
    <div class='kana'><%= link_to 'ひらがな', kana_posts_path %></div>
    <%# 結果一覧 %>
    <h5 class="align_center">記録フォーム</h5>
    <%= render partial: 'form', locals: { post: @post } %>
    <div class="heading-name">
      <h5 class="set-margin"><%= current_user.nickname %>さんの記録（<%= Time.now.month %>月）</h5>
    </div>
    <ul class="messages">
      <li class="heading-name-line"><li>
    </ul>
    <div class="align_center"><%= @monthly_post_count %> 件 | 合計：<%= @monthly_price_sum.to_s(:delimited) %>円</div>
    <% if @posts.present? %>
      <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
      <table>
        <%= render partial: 'post_list', collection: @posts, as: "post" %>
      </table>
      <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
    <% end %>
  </div>
</div>

app/views/posts/search.html.erb
<div class="container">
  <div class="contents">
    <div class='flash-message'><%= notice %></div>
    <div class='kana'><%= link_to 'ひらがな', kana_posts_path %></div>
    <%# 検索フォーム %>
    <h5 class="align_center">検索フォーム</h5>
    <div class="form_post">
      <%= search_form_for @q, url: search_posts_path(anchor: 'post_list') do |f| %>
        <table class="form_set_width_max">
          <tbody>
              <td class="form_set_width_search"><%= f.label :date_of_post_gteq, '日付' %></td>
              <td class="form_align_left">
                <%= f.date_field :date_of_post_gteq, id: "date1" %> から<br>
                <%= f.date_field :date_of_post_lteq, id: "date2" %> まで
              </td>
            </tr>
              <td><%= f.label :price_gteq, '金額' %></td>
              <td class="form_price_size form_align_left">
                <%= f.number_field :price_gteq, style: "width:60%", placeholder: '半角数字のみ', id: "price1" %> 円から<br>
                <%= f.number_field :price_lteq, style: "width:60%", placeholder: '半角数字のみ', id: "price2" %> 円まで
              </td>
            </tr>
            <tr>
              <td><%= f.label :memo1, 'メモ①' %></td>
              <td class="form_memo_size form_align_left">
                <%= f.text_field :memo1, style: "width:80%", class: 'form_memo', placeholder: 'OR検索できます', value: params[:q]&.dig(:memo1), id: "memo1" %>
              </td>
            </tr>
            <tr>
              <td><%= f.label :memo2, 'メモ②' %></td>
              <td class="form_memo_size form_align_left">
                <%= f.text_field :memo2, style: "width:80%", class: 'form_memo', placeholder: 'OR検索できます', value: params[:q]&.dig(:memo2), id: "memo2" %>
              </td>
            </tr>
            <tr>
              <td class="form_set_width_search">Good<br>yen?</td>
              <td class="form_align_left">
                <%= f.radio_button :select_yen_eq, '' %>
                <%= f.label :select_yen_eq, '指定なし', value: '' %><br>
                <%= f.radio_button :select_yen_eq, true %>
                <%= f.label :select_yen_eq, '「Good yen!」のみ', value: true %><br>
                <%= f.radio_button :select_yen_eq, false %>
                <%= f.label :select_yen_eq, '「あと一歩」のみ', value: false %>
              </td>
            </tr>
            <tr class="form_set_height">
              <td colspan="2">
                <%= f.button class: 'btn btn-outline-success' do %>
                  <i class="fa-solid fa-magnifying-glass fa-lg fa-fw" aria-hidden="true"></i>
                  一覧
                <% end %>
                <%= f.button class: 'btn btn-outline-success', name: 'export_csv', data: { confirm: "現在の条件で絞り込み、出力します。よろしいですか？\n（入力なしの場合、すべての記録が出力されます）"} do %>
                  <i class="fa-solid fa-file-lines fa-lg fa-fw" aria-hidden="true"></i>
                  CSV出力
                <% end %>
              </td>
            </tr>
            <tr class="form_set_height">
              <td colspan="2">
                <%= f.button class: 'btn btn-outline-success', name: 'show_donut' do %>
                  <i class="fa-solid fa-chart-pie fa-lg fa-fw" alt="円グラフ"></i>
                  全体
                <% end %>
                <%= f.button class: 'btn btn-outline-success', name: 'show_column' do %>
                  <i class="fa-solid fa-chart-simple fa-lg fa-fw" alt="縦向き棒グラフ"></i>
                  月ごと
                <% end %>
                <%= f.button class: 'btn btn-outline-success', name: 'show_bar' do %>
                  <i class="fa-solid fa-chart-simple fa-lg fa-fw bar_rotate" alt="横向き棒グラフ"></i>
                  月ごと
                <% end %>
              </td>
            </tr>
            <tr>
              <td colspan="2" class="align_center">
                <a href="/" id="reset_btn">
                  <i class="fa-solid fa-arrow-rotate-right fa-lg fa-fw" aria-hidden="true"></i>
                  検索条件をクリア
                </a>
            <tr>
          </tbody>
        </table>
      <% end %>
    </div>
    <%# /検索フォーム %>
    <%# 結果一覧 %>
    <div class="content" id="post_list">
      <div class="align_center">
        <%= render partial: 'query', locals: { period: @period, querys: @querys } %>
        <%= @post_count %> 件 | 合計：<%= @price_sum.to_s(:delimited) %>円<br>
      </div>
      <% if @posts.present? %>
        <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
        <div class="sort_info">＊項目名を押すと、<b>並べ替え</b>ができます</div>
          <table>
            <thead>
              <tr>
                <th rowspan="2" class="set-width-logo"><%= sort_link(@q, :select_yen, 'Good yen?') %></th>
                <th><%= sort_link(@q, :date_of_post, '日付') %></th>
                <th class="nowrap"><%= sort_link(@q, :price, '金額') %></th>
                <th rowspan="2" class="set-width"></th>
              </tr>
              <tr class="table-border">
                <th><%= sort_link(@q, :memo1, 'メモ①') %></th>
                <th><%= sort_link(@q, :memo2, 'メモ②') %></th>
              </tr>
            <thead>
            <tbody>
              <%= render partial: 'post_list', collection: @posts, as: "post" %>
            <tbody>
          </table>
        <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
      <% end %>
    </div>
    <%# /結果一覧 %>
  </div>
</div>