config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/disclaimer'
  get 'static_pages/privacy'
  devise_for :users
  root 'posts#index'
  resources :posts, except: :show do
    collection do
      get 'search'
      get 'select'
      get 'kana'
    end
  end
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>yen! | かんたん支出管理</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/4b4956428d.js" crossorigin="anonymous"></script>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= favicon_link_tag 'icon-192x192.png', rel: "icon", type: "image/png" %>
    <%= favicon_link_tag 'apple-touch-icon-180x180.png', rel: "apple-touch-icon", type: "image/png" %>
  </head>
  <body>
    <header>
      <div class="nav_left">
        <a href="/">
          <%= image_tag 'yen-logo.png', alt: "Topページリンク", class: "header-logo-img" %>
        </a>
      </div>
      <div class="nav_center">
        <ul class="nav-lists">
          <li>
            <%= link_to '記録する', new_post_path, class: "left-button nowrap" %>
          </li>
          <li>
            <%= link_to '振り返る', search_posts_path, class: "left-button nowrap"  %>
          </li>
          <li>
            <%= link_to select_posts_path do %>
              <i class="fa-solid fa-seedling fa-lg fa-fw left-button" alt="思い出Good_yen!リンク"></i>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="nav_right">
        <ul class="nav-lists">
          <% if user_signed_in? %>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <li><button type="button" class="btn btn-outline-success nowrap header_btn">ログアウト</button></li>
            <% end %>
          <% else %>
            <%= link_to new_user_session_path do %>
              <li><button type="button" class="btn btn-outline-success nowrap header_btn">ログイン</button></li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <div class="yen-info">
        <a class="footer_link" href="https://github.com/Asami119/good_yen" target="_blank">yen!</a>
        by <a href="https://twitter.com/asamiya_isseki" target="_blank">アサミヤ</a>
      </div>
      <div class="footer-nav">
        <ul class="footer-nav-lists">
          <li>
            <a href="/static_pages/disclaimer" class="info-link">利用規約</a>
          </li>
          <li>
            <a href="/static_pages/privacy">プライバシーポリシー</a>
          </li>
        </ul>
      </div>
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>